SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;


LOAD DATA LOCAL INFILE 'Data/atoma.csv' INTO TABLE atoma 
    FIELDS TERMINATED BY ',' 
    ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' 
    IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/as8eneis.csv' INTO TABLE as8eneis 
    FIELDS TERMINATED BY ',' 
    ENCLOSED BY '"' LINES 
    TERMINATED BY '\r\n' 
    IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/prosopiko.csv' INTO TABLE prosopiko 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/allergies_ashenon.csv' INTO TABLE Allergies_As8enwn --no
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' 
    IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/iatroi.csv' INTO TABLE Iatroi 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/tmhmata.csv' INTO TABLE Tmhmata 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/vardies.csv' INTO TABLE Vardies 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

--IATROI KAI TMHMATA CSV?

LOAD DATA LOCAL INFILE 'Data/wroi.csv' INTO TABLE Xwroi_Ai8ouses --EMPTY
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/klines.csv' INTO TABLE Klines 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SET FOREIGN_KEY_CHECKS = 1;
