SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;


LOAD DATA LOCAL INFILE 'Data/atoma.csv' INTO TABLE Atoma 
    FIELDS TERMINATED BY ',' 
    ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' 
    IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/as8eneis.csv' INTO TABLE as8eneis 
    FIELDS TERMINATED BY ',' 
    ENCLOSED BY '"' LINES 
    TERMINATED BY '\r\n' 
    IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/prosopiko.csv' INTO TABLE prosopiko 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

-- LOAD DATA LOCAL INFILE 'Data/allergies_asthenon.csv' INTO TABLE Allergies_As8enwn 
--     FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
--     LINES TERMINATED BY '\r\n' 
--     IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/iatroi.csv' INTO TABLE Iatroi 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/tmhmata.csv' INTO TABLE Tmhmata 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/vardies.csv' INTO TABLE Vardies 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

--IATROI KAI TMHMATA CSV?

LOAD DATA LOCAL INFILE 'Data/wroi.csv' INTO TABLE Xwroi_Ai8ouses 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/klines.csv' INTO TABLE Klines 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/icd_10.csv' INTO TABLE ICD_10 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/nosileies.csv' INTO TABLE Nosileies
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/axiologisi_iatrwn.csv' INTO TABLE Axiologisi_Iatrwn
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/axiologisi_noshleias.csv' INTO TABLE Axiologisi_Nosileias 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/iatroi_nosileias.csv' INTO TABLE Iatroi_nosileias
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/ergasthriakes_exetaseis.csv' INTO TABLE Ergasthriakes_Exetaseis
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/boithoi_praxeon.csv' INTO TABLE Boithoi_Praxeon
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/iatrikes_prakseis.csv' INTO TABLE Iatrikes_Praxeis 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/kostologisi.csv' INTO TABLE Kostologisi
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;


LOAD DATA LOCAL INFILE 'Data/ken_final.csv' INTO TABLE KEN
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/efhmeries.csv' INTO TABLE Efhmeries
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/farmaka.csv' INTO TABLE Farmaka 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;


LOAD DATA LOCAL INFILE 'Data/synthesi_farmakou.csv' INTO TABLE Synthesi_Farmakou
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/dioikitiko.csv' INTO TABLE Dioikitiko_Prosopiko 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/agwges.csv' INTO TABLE Agwges 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/eikones.csv' INTO TABLE Eikones 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'Data/eikones.csv' INTO TABLE Eikones 
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
    LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SET FOREIGN_KEY_CHECKS = 1;
